version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: ./dockerfiles
      dockerfile: nginx.root.dockerfile
    container_name: nginx-coursera
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - mysql
      - mailhog
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql-coursera
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mis
      MYSQL_USER: fred
      MYSQL_PASSWORD: zap
      MYSQL_ROOT_PASSWORD: zap
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.root.dockerfile
    container_name: php-coursera
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis-coursera
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - laravel

  composer:
    image: composer:2
    container_name: composer-coursera
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: root
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laravel

  npm:
    image: node:13.7
    container_name: npm-coursera
    volumes:
      - ./src:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.root.dockerfile
    container_name: artisan-coursera
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog-coursera
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - laravel
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-coursera
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    networks:
      - laravel